title: Sensorium Festival 2019
author:
  name: Unfold
  email: hello@unfold.is
ticket_url: https://ti.to/sensorium-festival-2019/sensorium-2019
metadata:
    description: Sensorium is the first Slovak festival making sense of creative technology. Sensorium gathers an international community of artists, designers, technologists and entrepreneurs for its conference programme, interactive exhibition, live performances and cross-disciplinary workshops.
    keywords: sensorium, conference, art, design, performance, technology, digital, bratislava, creative technology
    author: Unfold
    'og:title': Sensorium Festival 2019
    'og:description': Sensorium is the first Slovak festival making sense of creative technology. Sensorium gathers an international community of artists, designers, technologists and entrepreneurs for its conference programme, interactive exhibition, live performances and cross-disciplinary workshops.
    'og:type': website
    'og:url': http://sensorium.is/
    'og:site_name': Sensorium Festival 2019
    'og:image': http://sensorium.is/user/themes/imaginarious/images/social/sensorium-2018.jpg
    'og:locale': en_GB
    'og:locale:alternate': sk_SK
    'twitter:card' : summary_large_image
menu:
   - text: Tickets
     url: https://ti.to/sensorium-festival-2019/sensorium-2019
     classes: 'external link grow ba-l bw1 mt-1'
     newTab: true