absolute_urls: false

home:
  alias: '/modular'

pages:
  theme: imaginarious
  markdown:
    extra: false
  process:
    markdown: true
    twig: false
  dateformat:
    default: 'd/m/Y'                        # The default date format Grav expects in the `date: ` field
    short: 'jS M Y'                         # Short date format
    long: 'F jS \a\t g:ia'                  # Long date format

languages:
  supported:
    - en
    - sk
  override_locale: true
  include_default_lang: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true
  enable_asset_timestamp: true             # Enable asset timestamps

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  verify_peer: true
